name: city_weather
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.2
  auto_route: 3.2.4
  flutter_riverpod: 1.0.3
  ferry: 0.10.4
  gql: 0.13.1-alpha+1628192550785
  gql_dio_link: 0.2.1-alpha+1628192550872
  gql_exec: 0.3.1-alpha+1628192550793
  flex_color_scheme: 4.2.0
  intl_utils: 2.6.1
  injectable: 1.5.3
  get_it: 7.2.0
  load: 1.0.0
  json_annotation: 4.4.0
  enum_to_string: 2.0.1
  hive: 2.1.0
  hive_flutter: 1.1.0
  flutter_form_builder: 7.1.1
  form_builder_validators: 7.8.0

dependency_overrides:
  analyzer: 2.8.0
  dart_style: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0
  auto_route_generator: 3.2.3
  build_runner: 2.1.8
  ferry_generator: 0.4.4
  injectable_generator: 1.5.3
  json_serializable: 6.1.5
  hive_generator: 1.1.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
  arb_dir: lib/res/l10n
  output_dir: lib/res/l10n/generated
  use_deferred_loading: true
